apiVersion: v1
kind: ConfigMap
metadata:
  name: kubebench-config
data:
  kubebenchconfig.yaml: |
    """
    defaultWorkflowAgent:
      container:
        name: kubebench-workflow-agent
        image: ciscoai/kubebench-workflow-agent:latest
    defaultManagedVolumes:
      experimentVolume:
        name: kubebench-experiment-volume
        emptyDir: {}
      workflowVolume:
        name: kubebench-workflow-volume
        emptyDir: {}
    """
